Add support for custom fonts
dribia/dbt2pdf pull request #8
Opened 2024-09-03 12:31 UTC by hribera

2024-09-05 15:26 UTC, airibarne requested changes

2024-09-05 15:26 UTC, airibarne commented on dbt2pdf/font.py
> +    def __init__(self, path: str):
En general, sempre millor no sobreescriure l'`__init__` dels models de Pydantic. Crec que tot el que es fa aquí es pot fer amb validators, no? Que és una funcionalitat més controlada.

2024-09-05 15:26 UTC, airibarne commented on dbt2pdf/font.py
> +                if font.style in [FontStyle.REGULAR, FontStyle.BOLD, FontStyle.ITALIC]:
M'omple l'stdout de warnings això a mi, amb lo del logger de més avall desapareixeran, però still, podriem posar més valors a l'Enum:

```
ASSAMESE
BDITA
BENGALI
BI
BLACK
BLACKITALIC
BOLDITALIC
BOLDOBLIQUE
BOOK
BOOKOBLIQUE
C
DEMI
DEMIITALIC
DEMIOBLIQUE
DEVANAGARI
EXTRABOLD
EXTRALIGHT
GUJARATI
GURMUKHI
KANNADA
L
LI
LIGHT
LIGHTITALIC
LIGHTOBLIQUE
M
MALAYALAM
MEDIUM
MEDIUMITALIC
MI
ODIA
RI
ROMAN
SEMIBOLD
SEMIBOLDITALIC
TAMIL
TELUGU
TH
THIN
THINITALIC
```

2024-09-05 15:26 UTC, airibarne commented on dbt2pdf/pdf.py
> +                self.is_bold = True
Això entenc que controla si la font escollida té negreta o no, right? 

* Hi ha una opció més fàcil que és petar si no tenim negreta i fora, entenc que ho has volgut evitar, igual podem començar per aquí. 
* Si no, igual per simplificar el codi més avall pots crear-te un `self.bold_style` que sigui `"B"` quan l'hàgis trobat i `""` quan no, així no has d'anar posant `if self.is_bold`. 
* Also, feedback que no servirà per res perquè ja no tindrem `self.is_bold`, hauria estat més fàcil d'entendre si s'hagués dit `self.has_bold` o algo així hehe.

Fem lo del `self.bold_style`.

2024-09-05 15:26 UTC, airibarne commented on dbt2pdf/pdf.py
> +        self.set_font(family=font_family, style="B")
Aquesta línia si no trobes bold font no aplica, no? podria anar dins el if de dalt?

2024-09-05 15:26 UTC, airibarne commented
Vale @hribera no t'espantis, he deixat la review haha

Segurament la farem en dos passos, resolem aquests comments, i després igual en fem una altra una mica més de reorganització de lògica.

2024-09-06 07:46 UTC, hribera commented
@airibarne canvis fets, a veure com ho veus!

2024-10-09 14:56 UTC, hribera commented
@airibarne Repassa la PR a veure què et sembla.

He creat dos Warnings personalitzats a un mòdul `custom_warning.py`. No sé si calia fer-ho separat o es podia posar tot al mòdul `pdf.py`. 

Tema fonts queda així:
- Si la font existeix, la fa servir per crear el PDF.
- Si la font no existeix o no té estils ni *regular*, ni *bold*, ni *italics* (els supported per la llibreria `fpdf2`), crea el PDF amb valors default.
- Si la font existeix, però no té estil *regular*, crea el PDF amb els valors default.

Diga'm si et sembla bé o vols que canviï alguna cosa.

2024-10-12 09:43 UTC, airibarne submitted a review, later dismissed

2024-10-12 09:47 UTC, merged